# Generated by Django 6.1 on 2026-08-10 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa części')),
                ('manufacturer_code', models.CharField(max_length=50, unique=True, verbose_name='Kod producenta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jednostkowa (PLN)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Ilość w magazynie')),
            ],
            options={
                'verbose_name': 'Część',
                'verbose_name_plural': 'Części',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa usługi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena usługi (PLN)')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(verbose_name='Opis usterki')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Przyjęte'), ('IN_PROGRESS', 'W trakcie naprawy'), ('WAITING_FOR_PARTS', 'Oczekuje na części'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Anulowane')], default='ACCEPTED', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data przyjęcia')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
                ('services', models.ManyToManyField(blank=True, to='service.service', verbose_name='Wykonane usługi')),
            ],
            options={
                'verbose_name': 'Zlecenie serwisowe',
                'verbose_name_plural': 'Zlecenia serwisowe',
            },
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='service.serviceorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.part', verbose_name='Część')),
            ],
            options={
                'verbose_name': 'Wykorzystana część',
                'verbose_name_plural': 'Wykorzystane części',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('registration_number', models.CharField(max_length=15, unique=True, verbose_name='Numer rejestracyjny')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Numer VIN')),
                ('manufacture_year', models.PositiveIntegerField(verbose_name='Rok produkcji')),
                ('mileage', models.PositiveIntegerField(verbose_name='Przebieg (km)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='service.customer', verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Pojazd',
                'verbose_name_plural': 'Pojazdy',
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='service.vehicle', verbose_name='Pojazd'),
        ),
    ]
